import threeSum from './three-sum';

it('threeSum', () => {
  expect(threeSum([-1, 0, 1, 2, -1, -4])).toEqual(
    expect.arrayContaining([
      expect.arrayContaining([-1, 0, 1]),
      expect.arrayContaining([-1, -1, 2])
    ])
  );

  expect(threeSum([0, 1])).toEqual([]);
  expect(threeSum([0, 0, 0, 0])).toEqual([[0, 0, 0]]);
  expect(threeSum([0, 0, 0])).toEqual([[0, 0, 0]]);
  expect(threeSum([0, 0, 0, 0])).toEqual([[0, 0, 0]]);

  expect(
    threeSum([
      -14,
      -3,
      11,
      -3,
      12,
      -1,
      11,
      13,
      5,
      6,
      -11,
      -14,
      -6,
      11,
      -4,
      -15,
      3,
      -15,
      9,
      -10,
      13,
      -10,
      -9,
      -13,
      -12,
      12,
      -7,
      12,
      12,
      3,
      9,
      5,
      -14,
      -3,
      9,
      13,
      11,
      5,
      3,
      -6,
      -12,
      -1,
      -5,
      -3,
      -4,
      -2,
      -10,
      6,
      -10,
      14,
      3,
      -11,
      11,
      10,
      -9,
      7,
      -1,
      -9,
      4,
      -12,
      2,
      -2,
      8,
      3,
      3,
      -6,
      -7,
      -1,
      6,
      12,
      8,
      9,
      -12,
      10,
      -8,
      -1,
      -7,
      -3,
      12,
      -9,
      -12,
      1,
      -5,
      6,
      -12,
      -7,
      -2,
      2,
      -8,
      -13,
      5,
      9,
      -7,
      -10,
      -3,
      11,
      -1,
      -3,
      -13,
      -10,
      -14,
      11,
      6,
      -10,
      6,
      13,
      4,
      7,
      -13,
      -6,
      13,
      12,
      10,
      -15,
      4,
      13,
      -7,
      9,
      -8,
      0,
      4,
      4,
      -6,
      12,
      9,
      -2,
      0
    ])
  ).toEqual(
    expect.arrayContaining([
      expect.arrayContaining([-15, 1, 14]),
      expect.arrayContaining([-15, 2, 13]),
      expect.arrayContaining([-15, 3, 12]),
      expect.arrayContaining([-15, 4, 11]),
      expect.arrayContaining([-15, 5, 10]),
      expect.arrayContaining([-15, 6, 9]),
      expect.arrayContaining([-15, 7, 8]),
      expect.arrayContaining([-14, 0, 14]),
      expect.arrayContaining([-14, 1, 13]),
      expect.arrayContaining([-14, 2, 12]),
      expect.arrayContaining([-14, 3, 11]),
      expect.arrayContaining([-14, 4, 10]),
      expect.arrayContaining([-14, 5, 9]),
      expect.arrayContaining([-14, 6, 8]),
      expect.arrayContaining([-14, 7, 7]),
      expect.arrayContaining([-13, -1, 14]),
      expect.arrayContaining([-13, 0, 13]),
      expect.arrayContaining([-13, 1, 12]),
      expect.arrayContaining([-13, 2, 11]),
      expect.arrayContaining([-13, 3, 10]),
      expect.arrayContaining([-13, 4, 9]),
      expect.arrayContaining([-13, 5, 8]),
      expect.arrayContaining([-13, 6, 7]),
      expect.arrayContaining([-12, -2, 14]),
      expect.arrayContaining([-12, -1, 13]),
      expect.arrayContaining([-12, 0, 12]),
      expect.arrayContaining([-12, 1, 11]),
      expect.arrayContaining([-12, 2, 10]),
      expect.arrayContaining([-12, 3, 9]),
      expect.arrayContaining([-12, 4, 8]),
      expect.arrayContaining([-12, 5, 7]),
      expect.arrayContaining([-12, 6, 6]),
      expect.arrayContaining([-11, -3, 14]),
      expect.arrayContaining([-11, -2, 13]),
      expect.arrayContaining([-11, -1, 12]),
      expect.arrayContaining([-11, 0, 11]),
      expect.arrayContaining([-11, 1, 10]),
      expect.arrayContaining([-11, 2, 9]),
      expect.arrayContaining([-11, 3, 8]),
      expect.arrayContaining([-11, 4, 7]),
      expect.arrayContaining([-11, 5, 6]),
      expect.arrayContaining([-10, -4, 14]),
      expect.arrayContaining([-10, -3, 13]),
      expect.arrayContaining([-10, -2, 12]),
      expect.arrayContaining([-10, -1, 11]),
      expect.arrayContaining([-10, 0, 10]),
      expect.arrayContaining([-10, 1, 9]),
      expect.arrayContaining([-10, 2, 8]),
      expect.arrayContaining([-10, 3, 7]),
      expect.arrayContaining([-10, 4, 6]),
      expect.arrayContaining([-10, 5, 5]),
      expect.arrayContaining([-9, -5, 14]),
      expect.arrayContaining([-9, -4, 13]),
      expect.arrayContaining([-9, -3, 12]),
      expect.arrayContaining([-9, -2, 11]),
      expect.arrayContaining([-9, -1, 10]),
      expect.arrayContaining([-9, 0, 9]),
      expect.arrayContaining([-9, 1, 8]),
      expect.arrayContaining([-9, 2, 7]),
      expect.arrayContaining([-9, 3, 6]),
      expect.arrayContaining([-9, 4, 5]),
      expect.arrayContaining([-8, -6, 14]),
      expect.arrayContaining([-8, -5, 13]),
      expect.arrayContaining([-8, -4, 12]),
      expect.arrayContaining([-8, -3, 11]),
      expect.arrayContaining([-8, -2, 10]),
      expect.arrayContaining([-8, -1, 9]),
      expect.arrayContaining([-8, 0, 8]),
      expect.arrayContaining([-8, 1, 7]),
      expect.arrayContaining([-8, 2, 6]),
      expect.arrayContaining([-8, 3, 5]),
      expect.arrayContaining([-8, 4, 4]),
      expect.arrayContaining([-7, -7, 14]),
      expect.arrayContaining([-7, -6, 13]),
      expect.arrayContaining([-7, -5, 12]),
      expect.arrayContaining([-7, -4, 11]),
      expect.arrayContaining([-7, -3, 10]),
      expect.arrayContaining([-7, -2, 9]),
      expect.arrayContaining([-7, -1, 8]),
      expect.arrayContaining([-7, 0, 7]),
      expect.arrayContaining([-7, 1, 6]),
      expect.arrayContaining([-7, 2, 5]),
      expect.arrayContaining([-7, 3, 4]),
      expect.arrayContaining([-6, -6, 12]),
      expect.arrayContaining([-6, -5, 11]),
      expect.arrayContaining([-6, -4, 10]),
      expect.arrayContaining([-6, -3, 9]),
      expect.arrayContaining([-6, -2, 8]),
      expect.arrayContaining([-6, -1, 7]),
      expect.arrayContaining([-6, 0, 6]),
      expect.arrayContaining([-6, 1, 5]),
      expect.arrayContaining([-6, 2, 4]),
      expect.arrayContaining([-6, 3, 3]),
      expect.arrayContaining([-5, -5, 10]),
      expect.arrayContaining([-5, -4, 9]),
      expect.arrayContaining([-5, -3, 8]),
      expect.arrayContaining([-5, -2, 7]),
      expect.arrayContaining([-5, -1, 6]),
      expect.arrayContaining([-5, 0, 5]),
      expect.arrayContaining([-5, 1, 4]),
      expect.arrayContaining([-5, 2, 3]),
      expect.arrayContaining([-4, -4, 8]),
      expect.arrayContaining([-4, -3, 7]),
      expect.arrayContaining([-4, -2, 6]),
      expect.arrayContaining([-4, -1, 5]),
      expect.arrayContaining([-4, 0, 4]),
      expect.arrayContaining([-4, 1, 3]),
      expect.arrayContaining([-4, 2, 2]),
      expect.arrayContaining([-3, -3, 6]),
      expect.arrayContaining([-3, -2, 5]),
      expect.arrayContaining([-3, -1, 4]),
      expect.arrayContaining([-3, 0, 3]),
      expect.arrayContaining([-3, 1, 2]),
      expect.arrayContaining([-2, -2, 4]),
      expect.arrayContaining([-2, -1, 3]),
      expect.arrayContaining([-2, 0, 2]),
      expect.arrayContaining([-1, -1, 2]),
      expect.arrayContaining([-1, 0, 1])
    ])
  );
});
