name: CI pipeline
on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: yarn
    - name: lint
      run: |
        yarn lint
    - name: test
      run: |
        yarn test --runInBand
